const loginMockup = {
  'uid': '1x684985',
  'status': 'ok',
  'user': {
    'email': 'nacho@dreamers.com',
    'uid': '1x684985',
    'INDICE': 'ciudadanos',
    'ID': '1',
    'alias_principal': 'Nacho',
    'nivel': '10',
    'nombre_apellidos': 'Nacho Carmona',
    'alias': 'Nacho|guemachte|webmaster|Mr Dreamy|Nacho Carmona',
  },
};
const msgCollectionMockup = [{
  'ID': '28652',
  'name2': 'daledebil',
  'num': 58318,
  'date': 'Viernes, 9 de Diciembre de 2016 a las 23:20',
  'paginacion': '924',
  'emocion': 'http://dreamers.com/mrdreamy/vacio.gif',
  'nivel_ciudadano': '1',
  'comments': 'En lo que a rock progresivo español, y por no repetir un grupo, en lo particular seria El patio, de Triana, uno de los dos (no me decido) de Imán Califato Independiente y, a pesar de los pesares, Hijo del alba de Bloque.<BR>Probablemente hay algun disco, como elnde Crack o elnde Goticbque sean mejores pero Bloque fue, probablemente, elngeupo masnrepresentativo del prog patrio y debe estar en la terna. Este es su mejor disco.<BR>Por supuesto se admiten propuestas',
  'pais': 'Espaa',
  'FECHA_M': '1481322038',
  'encriptado': 'zfzmhhzmzxzdzihpzkza',
  'enigma': '1481300251',
  'publicados': 'daledebil,ciudadanos/17507',
  'FECHA_A': '1481322036',
  'ciudadano': '17507',
  'subject': '&quot;Si no hay casera nos vamos&quot;',
  'name': 'daledebil',
  'FECHA': '1481322036',
  'registro': 'si',
  'NUMERO_ENTRADA': '28652',
  'ciudad': 'Madrid',
  'REGISTRADO': 'abscenter',
  'INDICE': 'gritos/kingcrimson',
}, {
  'ID': '28651',
  'name2': 'Robertjazz',
  'num': 58317,
  'date': 'Viernes, 9 de Diciembre de 2016 a las 20:59',
  'paginacion': '924',
  'emocion': 'http://dreamers.com/mrdreamy/vacio.gif',
  'nivel_ciudadano': '1',
  'comments': 'Ok, es una muy buena trilogía, dos de esos discos (Durazno Sangrando y Películas) los escucho desde mi temprana adolescencia.<BR><BR>El sello Esoteric Records suele editar grupos progresivos ingleses de fines de los 60&rsquo; y comienzos de los 70&rsquo;, muchos de ellos absolutamente desconocidos, me resulta interesante bucear en esos discos (ahora que es tan fácil hacerlo, con un click...) Escuchen esto, pro ejemplo:<BR><BR>https://www.youtube.com/watch?v=4d8Jiq7S_yc<BR><BR><BR>Luego estos muchachos pasaron a llamarse &quot;Samurai&quot;, que también editó un disco en 1971.<BR><BR>Y hay mas grupos raros: Marsupilami, Paladin, Big Sleep, Jonesy...estos nombres se unen a otros que ya investigué hace un par de años con el libro de Norberto Cambiasso en mano, como High Tide (gran grupo de hard-rock progresivo con violin)<BR><BR>https://www.youtube.com/watch?v=DHIQkfp0s68',
  'pais': 'Arg',
  'FECHA_M': '1481313575',
  'encriptado': 'zaznhmznzzzdzihpzkza',
  'enigma': '1478275080',
  'FECHA_A': '1481313574',
  'publicados': 'Robertjazz,ciudadanos/26773',
  'ciudadano': '26773',
  'subject': '&quot;RECONOCER es capicua...&quot;',
  'FECHA': '1481313574',
  'name': 'Robertjazz',
  'registro': 'si',
  'NUMERO_ENTRADA': '28651',
  'REGISTRADO': 'abscenter',
  'ciudad': 'ColonState',
  'INDICE': 'gritos/kingcrimson',
}, {
  'ID': '85416',
  'name2': '.G.',
  'num': 58316,
  'dreamy': '1563',
  'date': 'Viernes, 9 de Diciembre de 2016 a las 20:35',
  'paginacion': '2713',
  'emocion': 'http://dreamers.com/indices/imagenes/dreamys.1563.IMAGEN1.gif',
  'nivel_ciudadano': '1',
  'comments': 'Buenas.<BR><BR>En noviembre de 2017 Dibbuks publicará el primer integral a color del Spirou de Franquin. La colección completa constará de ocho volúmenes.<BR><BR>Un saludo<BR>Felipe',
  'FECHA_M': '1481312160',
  'encriptado': 'znzihpzmzzzdzihpzkza',
  'enigma': '1355246312',
  'FECHA_A': '1481312159',
  'publicados': '.G.,ciudadanos/331',
  'ciudadano': '331',
  'subject': '&quot;Es usted un cabrón chiflado, doctor Cassidy. Me alegro de haberle llamado&quot;',
  'FECHA': '1481312159',
  'emocionalt': 'foros:zoe',
  'name': '.G.',
  'registro': 'si',
  'NUMERO_ENTRADA': '85416',
  'REGISTRADO': 'abscenter',
  'INDICE': 'gritos/invisibles',
}, {
  'ID': '28650',
  'name2': 'daledebil',
  'num': 58315,
  'date': 'Viernes, 9 de Diciembre de 2016 a las 18:37',
  'paginacion': '924',
  'emocion': 'http://dreamers.com/mrdreamy/vacio.gif',
  'nivel_ciudadano': '1',
  'comments': 'Con permiso de Roberto, la triada argentina la tengo clara... En lo que a prog se refiere claro',
  'pais': 'Espaa',
  'FECHA_M': '1481305024',
  'encriptado': 'zczphmzkzhzdzihpzkza',
  'enigma': '1481300251',
  'FECHA_A': '1481305023',
  'publicados': 'daledebil,ciudadanos/17507',
  'ciudadano': '17507',
  'subject': 'Re: &quot;Solo el que ensaya cien mil veces lo absurdo tararí tarará&quot;',
  'FECHA': '1481305023',
  'name': 'daledebil',
  'registro': 'si',
  'PREV': '28649',
  'NUMERO_ENTRADA': '28650',
  'REGISTRADO': 'abscenter',
  'ciudad': 'Madrid',
  'INDICE': 'gritos/kingcrimson',
}, {
  'ID': '28649',
  'name2': 'daledebil',
  'num': 58314,
  'date': 'Viernes, 9 de Diciembre de 2016 a las 18:35',
  'paginacion': '924',
  'emocion': 'http://dreamers.com/mrdreamy/vacio.gif',
  'nivel_ciudadano': '1',
  'NEXT': '28650',
  'comments': 'Sería cuestión de hacer ese top3 de diversos paises',
  'pais': 'Espaa',
  'FECHA_M': '1481304960',
  'encriptado': 'zszyhmzkzhzdzihpzkza',
  'enigma': '1481300251',
  'FECHA_A': '1481304959',
  'publicados': 'daledebil,ciudadanos/17507',
  'ciudadano': '17507',
  'subject': '&quot;Solo el que ensaya cien mil veces lo absurdo tararí tarará&quot;',
  'FECHA': '1481304959',
  'name': 'daledebil',
  'registro': 'si',
  'NUMERO_ENTRADA': '28649',
  'REGISTRADO': 'abscenter',
  'ciudad': 'Madrid',
  'INDICE': 'gritos/kingcrimson',
}, {
  'ID': '28648',
  'name2': 'jajani',
  'num': 58313,
  'date': 'Viernes, 9 de Diciembre de 2016 a las 18:04',
  'paginacion': '924',
  'emocion': 'http://dreamers.com/mrdreamy/vacio.gif',
  'nivel_ciudadano': '1',
  'comments': 'Hace mucho tiempo, un amigo mío se empeñó en lograr ese objetivo. Fue comprando los 2 a 5 discos mejores de cada país. En LP. En algunos casos se dejó una fuerte suma. Poco a poco los ha ido vendiendo de nuevo con ganancia de por medio. Yo sí me veo haciendo esa compra... pero no la venta.',
  'FECHA_M': '1481303083',
  'encriptado': 'zczihmznzhzdzihpzkza',
  'enigma': '1481303081',
  'FECHA_A': '1481303082',
  'publicados': 'jajani,ciudadanos/17426',
  'ciudadano': '17426',
  'subject': '&quot;Te daré un consejo... (de todas formas a mi ya no me sirve)&quot;',
  'FECHA': '1481303082',
  'name': 'jajani',
  'registro': 'si',
  'NUMERO_ENTRADA': '28648',
  'REGISTRADO': 'abscenter',
  'INDICE': 'gritos/kingcrimson',
}, {
  'ID': '28647',
  'name2': 'daledebil',
  'num': 58312,
  'date': 'Viernes, 9 de Diciembre de 2016 a las 17:17',
  'paginacion': '924',
  'emocion': 'http://dreamers.com/mrdreamy/vacio.gif',
  'nivel_ciudadano': '1',
  'comments': 'Tras este parentesis vuelvo a la trilogía fantastica del rock argentino: Anabelas, de Bubu; Peliculas, de La maquina de hacer pajaros y Durazno Sangrando, de Invisible.<BR>Por cierto, con esto me he enterado que un durazno es un melocotón<BR>Que buenos discos son esos tres.<BR>La verdad es que, si lo analizas, con que cojas solo los dos o tres discos excepcionales que, a buen seguro, se han hecho en la mayor parte de los países, ya daría para una larga lista. Esto de la musica es inabarcable',
  'FECHA_M': '1481300252',
  'encriptado': 'zfzhhpzdzizfzihpzkza',
  'enigma': '1481300251',
  'FECHA_A': '1481300251',
  'publicados': 'daledebil,ciudadanos/17507',
  'ciudadano': '17507',
  'subject': '&quot;Cinco de cada cuatro se preguntan donde demonios está el quinto...&quot;',
  'FECHA': '1481300251',
  'name': 'daledebil',
  'registro': 'si',
  'NUMERO_ENTRADA': '28647',
  'REGISTRADO': 'abscenter',
  'INDICE': 'gritos/kingcrimson',
}, {
  'ID': '2648',
  'name2': 'BC',
  'num': 58311,
  'date': 'Viernes, 9 de Diciembre de 2016 a las 16:48',
  'paginacion': '85',
  'comments': 'Hola necesito hablar. No se que decisión tomar.<BR>Mi whatsapp 829-271-0517',
  'email': 'contregadob@gmail.com',
  'pais': 'República Dominicana',
  'FECHA_M': '1481298537',
  'encriptado': 'zczvhszfzizfzihpzkza',
  'enigma': '1481298536',
  'FECHA_A': '1481298537',
  'email2': 'contregadob@gmail.com',
  'subject': 'Incertidumbre',
  'FECHA': '1481298537',
  'name': 'BC',
  'anonimo': 'si',
  'registro': 'si',
  'NUMERO_ENTRADA': '2648',
  'INDICE': 'gritos/amistad',
}, {
  'ID': '85415',
  'name2': 'Gibarian',
  'num': 58308,
  'date': 'Viernes, 9 de Diciembre de 2016 a las 15:48',
  'paginacion': '2713',
  'emocion': 'http://dreamers.com/mrdreamy/color/d164.gif',
  'nivel_ciudadano': '1',
  'comments': '¡Qué envidia poder disfrutar de &quot;The Wire&quot; por primera vez!',
  'FECHA_M': '1481294906',
  'encriptado': 'zvzmhpzkzizfzihpzkza',
  'enigma': '1481294905',
  'FECHA_A': '1481294905',
  'publicados': 'Gibarian,ciudadanos/8499',
  'ciudadano': '8499',
  'subject': 'Re(2): Premios Dixto 2016',
  'FECHA': '1481294905',
  'name': 'Gibarian',
  'registro': 'si',
  'PREV': '85414',
  'NUMERO_ENTRADA': '85415',
  'REGISTRADO': 'abscenter',
  'INDICE': 'gritos/invisibles',
}, {
  'ID': '85414',
  'name2': 'Alpargata Jam',
  'num': 58302,
  'date': 'Viernes, 9 de Diciembre de 2016 a las 15:19',
  'paginacion': '2713',
  'emocion': 'http://dreamers.com/mrdreamy/color/d217.gif',
  'nivel_ciudadano': '2',
  'NEXT': '85415',
  'comments': '***¡¡¡PELIS!!!!***<BR>De lo que he visto este año, recuerdo con cariño:<BR><BR>*Recientes (más o menos) y mezclando cine comercial con gafapastil:<BR>- Los odiosos ocho, aunque no me parezca ni mucho menos redonda.<BR>- Ha vuelto, una comedia sobre el regreso de Hitler muy bien llevada.<BR>- Tropa de Élite 2, peliculón al que el título no hace justicia.<BR>- 45 años, cruel relato de la degeneración de una relación de pareja y la vejez.<BR>- Cloverfield Lane 10, divertidisima<BR>- Green Room, una peli de las chungas, con fallos a tutiplen pero que me divirtió lo suyo.<BR>- Techo y comida. Para mi se ha hablado muy poco de esta peli española y me parece una lástima porque es cojonuda. Además ese final homenaje a Tiempos Modernos me ganó.<BR>- El libro de la Selva. Sí, con la peque tengo sobredosis de pelis infantiles y esta me pareció muy conseguida.<BR><BR>¡¡Y no destaco ninguna de superhéroes porque las de este año me han parecido muy malas!!¡¡Dita sea!!<BR><BR>***¡¡¡SERIES TV!!!!***<BR>Aquí voy más desactualizado que la mayoría de dixtópicos...así que no se soprendan con las votaciones:<BR>- The Wire, pues eso...<BR>- Juego de Tronos, me lo paso teta que se le va a hacer...soy uno más<BR>- Stranger Things, cuando una serie hace que me la trague entera en 2 días toca reseñarla. ¡Regreso a los 80!<BR><BR>Y no, de momento no pongo Westworld (con 5 episodios vistos), lo que me hace entrar directamente en la lista negra de Xoota.<BR><BR><BR>***¡¡¡LIBROS!!!!***<BR>Debo leer más, debo leer más, debo leer más...<BR>- Nada de Manchette, un clásico de la novela negra pero que de género tiene poco...un manual de porque el terrorismo no consigue nada en la lucha por un mundo mejor. Cojonudo.<BR>- La II Guerra Mundial de Churchill, llevaré una cuarta parte leída (memorias tochales mediante) pero vale la pena echarle un vistazo pese a ser cualquier cosa menos neutral. Por ejemplo, el muy cabrón pasa de largo de la Guerra Civil española sabiendo que ahí es muy díficil justificar las decisiones del noble y heroico pueblo británico (cuando además una derrota de Franco bien podría haber cambiado el curso de los acontecimientos...que a esos &quot;posibles cambios si se hubiera hecho esto en lugar de aquello&quot; dedica gran parte de sus memorias.<BR>- Días de destrucción, días de revuelta. Ilustrado por Sacco y que ofrece un relato desgarrador de los marginados (actualmente) por el capitalismo en los EEUU. Especialmente flipante la parte dedicada a los pueblos indígenas.',
  'minimsgs': '2',
  'pais': 'Espaï¿½a',
  'FECHA_M': '1481293230',
  'encriptado': 'zazhhsznzizfzihpzkza',
  'enigma': '1460067727',
  'FECHA_A': '1481293165',
  'publicados': 'Alpargata Jam,ciudadanos/3278',
  'ciudadano': '3278',
  'subject': 'Re: Premios Dixto 2016',
  'FECHA': '1481293165',
  'name': 'Alpargata Jam',
  'registro': 'si',
  'PREV': '85413',
  'NUMERO_ENTRADA': '85414',
  'REGISTRADO': 'abscenter',
  'ciudad': 'Valencia',
  'INDICE': 'gritos/invisibles',
}];
const mockup = {
  active: false,
  loginMockup,
  msgCollectionMockup,
};

export default mockup;